---
- name: Install Java 1.8
  apt: name=openjdk-8-jdk

- name: Install tomcat8
  apt: name=tomcat8 state=present

- name: Install tomcat8-user
  apt: name=tomcat8-user

- name: Creates directory
  file: path=/app/ state=directory
  
- name: Symlink install directory
  file: src=/etc/tomcat8 path=/usr/share/tomcat8/conf state=link 

- name: stopping service 
  service: name=tomcat8 state=stopped

- name: Create tomcat instance 
  shell: tomcat8-instance-create -p {{ tomcat_http }} -c {{ tomcat_shutdown }} /app/{{ tomcat_name }}
  
- name: create start up script
  template:  src=tomcat.service dest=/lib/systemd/system/tomcat-{{ tomcat_name }}.service

- name: Changing ports in server.xml file
  shell: sed -i 's/8005/{{ tomcat_shutdown }}/g; s/8080/{{ tomcat_http }}/g; s/8009/{{ tomcat_ajp }}/g' /app/{{ tomcat_name }}/conf/server.xml

- name: Change ownership of Tomcat installation
  file: path=/app/{{ tomcat_name }} owner=tomcat8 group=tomcat8 state=directory recurse=yes
  
- name: Start Tomcat {{ tomcat_name}}
  service: name="tomcat-{{ tomcat_name}}" state=started enabled=yes

- name: create start up script
  template:  src=tomcat-logrotate dest=/etc/logrotate.d/tomcat-logrotate-{{ tomcat_name }}
